
services:
  mongodb-auth:
    image: mongo:6.0
    container_name: mongodb-auth
    ports:
      - "27018:27017"
    volumes:
      - mongo_auth_data:/data/db

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb-auth:27017
    depends_on:
      - mongodb-auth

  mongodb-products:
    image: mongo:6.0
    container_name: mongodb-products
    ports:
      - "27019:27017"
    volumes:
      - mongo_products_data:/data/db

volumes:
  mongo_auth_data:
  mongo_products_data:
