
version: "3.9"
name: impochina

services:
  sourcing:
    build:
      context: ./impochina-sourcing
    container_name: impochina-sourcing
    env_file:
      - ./impochina-sourcing/.env
    ports:
      - "3000:3000"
    # DEV: hot-reload
    volumes:
      - ./impochina-sourcing:/app
      - /app/node_modules
    command: npm run start:dev
    profiles: ["dev"]

  # PROD local (sin bind-mount; usa Runtime del Dockerfile)
  sourcing-prod:
    build:
      context: ./impochina-sourcing
    container_name: impochina-sourcing-prod
    env_file:
      - ./impochina-sourcing/.env
    ports:
      - "3000:3000"
    profiles: ["prod"]

  # Descomenta cuando los uses
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
  #     POSTGRES_DB: impochina
  #   ports: ["5432:5432"]
  #   volumes: [pgdata:/var/lib/postgresql/data]
  #   profiles: ["dev","prod"]

  # redis:
  #   image: redis:7-alpine
  #   ports: ["6379:6379"]
  #   profiles: ["dev","prod"]

#volumes:
#  pgdata:
