# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"8\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t2W\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=20
  _globals['_VALIDATETOKENREQUEST']._serialized_end=57
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=59
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=115
  _globals['_AUTHSERVICE']._serialized_start=117
  _globals['_AUTHSERVICE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
