version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: ms2-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: impochina_orders
    volumes:
      - mongo_data:/data/db

  ms2-orders:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms2-orders
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: impochina_orders
      AUTH_JWT_SECRET: devsecret
      AUTH_JWT_ALG: HS256
      ALLOW_ORIGINS: http://localhost:3000
      PORT: "8000"
    depends_on:
      - mongo
    ports:
      - "8000:8000"

volumes:
  mongo_data:
