# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc/auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp/grpc/auth.proto\x12\x04\x61uth\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"?\n\rValidateReply\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\nLoginReply\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2y\n\x0b\x41uthService\x12;\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x13.auth.ValidateReply\x12-\n\x05Login\x12\x12.auth.LoginRequest\x1a\x10.auth.LoginReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEREQUEST']._serialized_start=29
  _globals['_VALIDATEREQUEST']._serialized_end=61
  _globals['_VALIDATEREPLY']._serialized_start=63
  _globals['_VALIDATEREPLY']._serialized_end=126
  _globals['_LOGINREQUEST']._serialized_start=128
  _globals['_LOGINREQUEST']._serialized_end=178
  _globals['_LOGINREPLY']._serialized_start=180
  _globals['_LOGINREPLY']._serialized_end=229
  _globals['_AUTHSERVICE']._serialized_start=231
  _globals['_AUTHSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
